### PR TITLE
chore: add substra-backend-22.1.2-1 chart

### PR DESCRIPTION
**Pull request by Kelvin-M**
This chart uses patched substra-backend images `0.31.1` containing a [bugfix](https://github.com/Substra/substra-backend/releases/tag/0.31.1) backported from https://github.com/Substra/substra-backend/pull/491.

See the diff here: https://github.com/Substra/substra-backend/compare/0.31.0...0.31.1

This chart will be useful to:

- Upgrade substra-backend images to `0.31.x` in production.
- Be a part of the upcoming 0.22 Substra release (currently pre-release / under test)

### CODE REVIEW

**Comment by AlexandrePicosson** [comment]
Could you explain why you need this chart and what are the changes inside ?

**Review by AurelienGasser — APPROVED** [review]

**Comment by AurelienGasser** [comment]
@AlexandrePicosson Please see the updated PR description.

**Review by AlexandrePicosson — CHANGES_REQUESTED** [review]
There is no need to publish a new chart for that, you can just update the values.

**Comment by Kelvin-M** [comment]
> There is no need to publish a new chart for that, you can just update the values.

If values have changed (even if only image tag version) in the chart we need to publish a new version no ?

**Comment by AlexandrePicosson** [comment]
But the main issue I see is that based on semver you are issuing a new pre-release and that does not make much sense. IMO you can still use the chart version `22.1.2` as it is compatible with the version 0.31.x of the backend. Maybe we should change our versioning  scheme if that is not satisfying.

**Pull request closed without merging**
